name: Release-snapshot

on:
  - pull_request
  - push

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
        ocaml-version:
          - 4.12.1
        with-satysfi:
          - false
        oldest-dependencies:
          - false
    runs-on: ${{ matrix.os }}
    env:
      OPAMSOLVERTIMEOUT: 3600
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          dune-cache: true
          opam-pin: false

          cache-prefix: "oldestdeps-${{ matrix.oldest-dependencies }}-satysfi-${{ matrix.with-satysfi }}"

      - name: Check validity of the snapshot OPAM files
        run: |
          opam lint --strict *.opam

      - name: Add SATySFi-related repos
        run: |
          opam repository add satysfi-external https://github.com/gfngfn/satysfi-external-repo.git
          opam repository add satyrographos https://github.com/na4zagin3/satyrographos-repo.git
          opam update

      - name: Install Satyrographos
        if: ${{ ! matrix.oldest-dependencies }}
        run: |
          opam install satyrographos-snapshot-stable --yes

      # The tarball must contain dist/ directory rather than archiving dist/ directly
      - name: Create snapshot tarball
        run: |
          opam exec -- satyrographos install --output tarball/dist --copy
          tar acf satysfi-snapshot-stable.tar.xz tarball/
          tar acf satysfi-snapshot-stable.tar.zstd tarball/

      - name: Publish tarball as workflow artifact
        uses: actions/upload-artifact@v2
        with:
          name: satysfi-snapshot-stable.tar.xz
          path: |
            satysfi-snapshot-stable.tar.xz

      - name: Publish tarball as workflow artifact
        uses: actions/upload-artifact@v2
        with:
          name: satysfi-snapshot-stable.tar.zstd
          path: |
            satysfi-snapshot-stable.tar.zstd